tagallery/__init__.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

#   Tagallery, a tag based web gallery
#   Copyright (C) 2014  Julio Biason
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""The main module for Tagallery"""

tagallery/blueprints/__init__.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

#   Tagallery, a tag based web gallery
#   Copyright (C) 2014  Julio Biason
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Blueprints for Tagallery"""

tagallery/blueprints/admin.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

#   Tagallery, a tag based web gallery
#   Copyright (C) 2014  Julio Biason
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Administration base."""

from flask import Blueprint
from flask import render_template

from flask.ext.login import login_required

admin = Blueprint('admin', __name__)


@admin.route('/', methods=['GET'])
@login_required
def dashboard():
    return render_template('admin/dashboard.html')

tagallery/blueprints/index.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

#   Tagallery, a tag based web gallery
#   Copyright (C) 2014  Julio Biason
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""The main page."""

import logging

from flask import Blueprint
from flask import render_template
from flask import current_app

from pony.orm import count
from pony.orm import select

from tagallery.database import Image

log = logging.getLogger('tragallery.index')

index = Blueprint('index',
                  __name__)


@index.route('/', defaults={'page': 1})
@index.route('/<int:page>')
def all_images(page):
    return render_template('index.html',
                           total_images=_image_count(),
                           thumbnail_size=current_app.config['THUMBNAIL_SIZE'])


def _image_count():
    """Return the number of images, either from the db or in the app
    "cache"."""
    total_images = current_app.config['_IMAGES']
    if not total_images:
        total = list(select(count(record) for record in Image))
        log.debug(total)
        total_images = total[0]
        current_app.config['_IMAGES'] = total_images

    log.debug('{0} images in the database'.format(total_images))
    return total_images

tagallery/blueprints/upload.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

#   Tagallery, a tag based web gallery
#   Copyright (C) 2014  Julio Biason
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Image upload module."""

import os
import os.path
import datetime
import logging

from werkzeug import secure_filename

from flask import Blueprint
from flask import render_template
# from flask import redirect
from flask import url_for
from flask import current_app
from flask import request
from flask import jsonify
from flask import flash
from flask import abort
from flask import send_from_directory

from flask.ext.login import login_required

from PIL import Image as ImageFile

from tagallery.database import Image
from tagallery.database import Tag

from tagallery.storage import partition
from tagallery.storage import thumbname

upload = Blueprint('upload', __name__)

LOG = logging.getLogger('tagallery.blueprints.upload')


@upload.route('/', methods=['GET'])
@login_required
def dashboard():
    return render_template('upload/upload.html')
    # return redirect(url_for("upload.from_browser"))
    # return render_template('upload/dashboard.html')


@upload.route('/browser/upload/', methods=['POST'])
@login_required
def upload_file():
    fileobj = request.files['file']
    response = {'status': 'UNKNOWN', 'filename': None}
    if fileobj:
        filename = secure_filename(fileobj.filename)
        path = os.path.join(current_app.config['IMAGE_PATH'],
                            partition(filename))
        try:
            os.makedirs(path)
        except os.error:
            pass    # already exists

        final_filename = os.path.join(path, filename)
        fileobj.save(final_filename)
        response['status'] = 'OK'
        response['filename'] = final_filename

        LOG.debug('File {file} saved on disk'.format(file=final_filename))

    return jsonify(response)


@upload.route('/save/', methods=['POST'])
@login_required
def save():
    filename = request.values.get('filename')
    title = request.values.get('title')
    form_tags = request.values.get('tags', '').split(',')

    if len(form_tags) == 0:
        flash('Must have at least one tag', 'alert')

    tags = []
    for single_tag in form_tags:
        if not single_tag:
            continue

        LOG.debug('Searching for tag {0}'.format(single_tag))
        tag = Tag.get(tag=single_tag)
        if not tag:
            LOG.debug('Tag {0} not found, creating new'.format(single_tag))
            tag = Tag(tag=single_tag)
        tags.append(tag)

    Image(title=title,
          tags=tags,
          created_at=datetime.datetime.utcnow(),
          filename=filename)

    LOG.debug('Image saved')

    thumb = ImageFile.open(filename)
    size = current_app.config['THUMBNAIL_SIZE']
    thumb.thumbnail((size, size),
                    ImageFile.ANTIALIAS)
    thumb.save(thumbname(filename))

    LOG.debug('Thumbnail {0} created'.format(thumbname(filename)))

    flash('Upload completed with success')

    return render_template('upload/from_browser.html', source='browser')


@upload.route('/queue/', methods=['GET'])
@login_required
def queue():
    """Return a list of files waiting in the incoming directory."""
    root = os.path.expanduser(current_app.config['IMAGE_QUEUE'])
    LOG.debug('Queue dir: {0}'.format(root))
    result = {'status': 'OK', 'files': []}

    try:
        for filename in os.listdir(root):
            LOG.debug('Found file: {0}'.format(filename))

            # pruning unwanted files
            if not filename.lower().endswith('.png') and \
                    not filename.lower().endswith('.jpg') and \
                    not filename.lower().endswith('.gif'):
                continue

            result['files'].append({
                'url': url_for('upload.serve_queue', filename=filename),
                'title': filename
            })
    except OSError:
        # the queue directory does not exist
        pass

    return jsonify(result)


@upload.route('/queue/image/', methods=['GET'])
@login_required
def serve_queue():
    """Serve an image directly from the queue."""
    filename = request.values.get('filename')
    if not filename:
        abort(400)

    queue_dir = os.path.expanduser(current_app.config['IMAGE_QUEUE'])

    return send_from_directory(queue_dir, filename)

tagallery/blueprints/users.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

#   Tagallery, a tag based web gallery
#   Copyright (C) 2014  Julio Biason
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""User management."""

from flask import Blueprint
from flask import render_template
from flask import request
from flask import flash
from flask import redirect
from flask import url_for

from flask.ext.login import login_user
from flask.ext.login import logout_user

from tagallery.database import User

# from pony.orm import db_session
from pony.orm import ObjectNotFound

import logging
import crypt

users = Blueprint('users', __name__)

log = logging.getLogger('tagallery.users')


@users.route('/login/', methods=['GET'])
def show_login():
    return render_template('users/login.html')


@users.route('/login/', methods=['POST'])
def make_login():
    username = request.values.get('username')
    password = request.values.get('password')

    if not username:
        log.debug('Missing username')
        flash('Username is required', 'alert')
        return render_template('users/login.html', username=username)

    if not password:
        log.debug('Missing password')
        flash('Password is required', 'alert')
        return render_template('users/login.html', username=username)

    salt = username[0] + username[-1]

    crypted = crypt.crypt(password, salt)
    user = None
    try:
        user = User.get(login=username, password=crypted)
    except ObjectNotFound:
        user = None

    log.debug('User = {0}'.format(user))
    if not user:
        flash('Invalid username/password', 'alert')
        return render_template('users/login.html', username=username)

    login_user(user, remember=True)
    return redirect(request.args.get('next') or url_for('index.all_images'))


@users.route('/logout/', methods=['GET'])
def logout():
    logout_user()
    return redirect(url_for('index.all_images'))

tagallery/templates/upload/dashboard.html
{% extends "base.html" %}

{% block content %}
<div class='row'>
	<div class='columns large-12'>
		<dl class='sub-nav'>
			<dt>Upload source:</dt>
			<dd {% if source == "browser" %}class="active"{% endif %}><a href='{{ url_for("upload.from_browser") }}'>Browser</a></dd>
			<dd {% if source == "upload_dir" %}class="active"{% endif %}><a href='{{ url_for("upload.from_uploaddir") }}'>Upload dir</a></dd>
		</dl>
	</div>

	<div class='columns large-12'>
		{% block upload_form %}
		{% endblock upload_form %}
	</div>
</div>
{% endblock content %}

tagallery/templates/upload/from_browser.html
{% extends "upload/dashboard.html" %}

{% block upload_form %}
<form method='POST' action='{{ url_for("upload.save") }}' id='from-browser-form'>
	<input type='hidden' name='filename' value=''>
	<div class='row'>
		<div class='columns large-12'>
			<div id='dropzone'>
				<div class='placeholder'>
					Drop image here or click to select.
				</div>
			</div>

			<div class='hide'>
				<input type='file' name='upload_file'>
			</div>

			<div class='progress radius'>
				<span class='meter' style="width:0"></span>
			</div>
		</div>
	</div>

	<div class='row'>
		<div class='columns large-10 large-offset-1'>
			<label for='input_title'>
				Title:
			</label>
			<input type='text' placeholder='Title' name='title'>
		</div>
	</div>

	<div class='row'>
		<div class='columns large-10 large-offset-1'>
			<label for='input_tags'>
				Tags:
			</label>
			<input type='text' placeholder='Tags' name='tags' style='width:100%'>
		</div>
	</div>

	<div class='row'>
		<div class='columns large-12 form-close'>
			<button class='small button radius save'>Save</button>
			<button class='small button radius secondary cancel'>Cancel</button>
		</div>
	</div>
</form>
{% endblock upload_form %}

{% block styles %}
	<style>
		#dropzone {
			width: 100%;
			height: 450px;
			border: 1px solid rgb(204,204,204);
		}

		#dropzone div.placeholder {
			text-align: center;
			font-style: italic;
			font-weight: 600;
			color: #aaa;
			line-height: 450px;
		}

		#dropzone img {
			display: block;
			margin-left: auto;
			margin-right: auto;
		}

		.form-close {
			text-align: center;
			margin-top: 15px;
		}

		.drag-enter {
			background: rgb(240, 240, 240);
		}
	</style>
{% endblock styles %}

{% block scripts %}
<script src='{{ url_for("static", filename="js/tagallery-upload.js") }}'></script>
<script>
	$(function () {
		disableSave();		/* because there is no image yet */
		$('input[name="tags"]').select2({
			tags: true,
			tokenSeparators: [','],
			multiple: true,
			createSearchChoice: function (term, data) {
				if ($(data).filter(function () {
					return this.text.localeCompare(term) === 0;
				}).length === 0) {
					return {
						id: term,
						text: term
					}
				}
			}
		});

		$('#dropzone')
			.on('click', function () {
				$('input[name="upload_file"]').click();
			})
			.on('dragover', function (ev) {
				$(this).addClass('drag-enter');
				ev.preventDefault();
				ev.stopPropagation();
			})
			.on('dragend', function (ev) {
				$(this).removeClass('drag-enter');
				ev.preventDefault();
				ev.stopPropagation();
			})
			.on('drop', function (ev) {
				$(this).removeClass('drag-enter');
				ev.preventDefault();
				disableSave();
				uploadFiles(ev.originalEvent.dataTransfer.files,
							"{{ url_for('upload.upload_file') }}",
							postUpload);
			});

		$('input[name="upload_file"]').on('change', function () {
			disableSave();
			uploadFiles($(this).get(0).files,
			            "{{ url_for('upload.upload_file') }}",
						postUpload);
		});
	});
</script>
{% endblock scripts %}

{# vim:set ft=jinja: #}

tagallery/templates/upload/from_uploaddir.html
{% extends "upload/dashboard.html" %}

{% block upload_form %}
	Uploading from uploadir
{% endblock upload_form %}

tagallery/templates/upload/upload.html
{% extends "base.html" %}

{% macro _image(thumbnail_url=None, klass=None) %}
	<div class='{% if klass %}{{ klass }}{% endif %} holder'>
		<form method='POST' action='{{ url_for("upload.save") }}'>
			<input type='hidden' name='filename' value=''>

			<div class='row'>
				<div class='small-12'>
					<div class='image-title'>
					</div>
				</div>
			</div>

			<div class='image'>
			</div>

			<div class='row'>
				<div class='small-12 columns'>
					<div class='progress radius success invisible'>
						<span class='meter'></span>
					</div>
				</div>
			</div>

			<div class='row'>
				<div class='small-2 columns'>
					<label class='right inline'>Title</label>
				</div>

				<div class='small-10 columns'>
					<input type='text' placeholder='Title' value='' name='title'>
				</div>
			</div>

			<div class='row'>
				<div class='small-2 columns'>
					<label class='right inline'>Tags</label>
				</div>

				<div class='small-10 columns'>
					<input type='text' placeholder='Tags' value='' name='tags'>
				</div>
			</div>

			<div class='row'>
				<div class='small-9 small-offset-3 columns form-close'>
					<button class='tiny button radius save'>Save</button>
				</div>
			</div>
		</form>
	</div>
{% endmacro %} {# _image #}

{% block content %}
<div id='upload'>
	{{ _image(klass="template hide") }}
	{# {{ _image(klass="new") }} #}
</div>
{% endblock content %}

{% block styles %}
<style>
#upload {
	height: 600px;
	overflow-x: scroll;
	overflow-y: hidden;
	white-space: nowrap;
}

#upload div.holder {
	display: inline-block;
	width: 400px;
	/* margin-right: 15px; */
	padding: 5px;
}

#upload div.holder.just-uploaded {
	background: #baffff;
}

#upload div.holder div.image-title {
	font-weight: 700;
	text-align: center;
	margin-bottom: 3px;
	text-overflow: ellipsis;
	overflow: hidden;
	width: 390px;
}

#upload div.holder div.image {
	display: block;
	/* border: 1px dashed gray; */
	height: 290px;
	width: 390px;
	margin-bottom: 10px;
}

#upload div.holder.new div.image {
	border: 1px dashed gray;
}

#upload div.holder .progress {
	height: 10px;
	padding: 1px;
}

#upload div.image img {
	display: block;
	margin-left: auto;
	margin-right: auto;
	margin-top: auto;
	margin-bottom: auto;
}

#upload div.hide {
	display: none !important;	/* foundation doesn't make this important */
}

#upload div.form-close {
	text-align: center;
}

#upload .invisible {
	visibility: hidden;
}
</style>
{% endblock styles %}

{% block scripts %}
<script src='{{ url_for("static", filename="js/tagallery-upload.js") }}'></script>
<script>
	(function () {
		$('div.holder.new input[name="tags"]').select2({
			tags: true,
			tokenSeparators: [','],
			multiple: true,
			createSearchChoice: function (term, data) {
				if ($(data).filter(function () {
					return this.text.localeCompare(term) === 0;
				}).length === 0) {
					return {
						id: term,
						text: term
					}
				}
			}
		});

		var dropzone = addImage("Upload new", "");
		dropzone.classList.add('new');
		dropzone.ondragover = function () { return false; }
		dropzone.ondragend = function () { return false; }
		dropzone.ondrop = function (ev) {
			ev.preventDefault();
			uploadFiles(ev.dataTransfer.files, "{{ url_for("upload.upload_file") }}");
		}

		getQueue('{{ url_for("upload.queue") }}');
	})();
</script>
{% endblock scripts %}