tagallery/__init__.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

#   Tagallery, a tag based web gallery
#   Copyright (C) 2014  Julio Biason
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""The main module for Tagallery"""

tagallery/blueprints/__init__.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

#   Tagallery, a tag based web gallery
#   Copyright (C) 2014  Julio Biason
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Blueprints for Tagallery"""

tagallery/blueprints/admin.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

#   Tagallery, a tag based web gallery
#   Copyright (C) 2014  Julio Biason
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Administration base."""

from flask import Blueprint
from flask import render_template

from flask.ext.login import login_required

admin = Blueprint('admin', __name__)


@admin.route('/', methods=['GET'])
@login_required
def dashboard():
    return render_template('admin/dashboard.html')

tagallery/blueprints/index.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

#   Tagallery, a tag based web gallery
#   Copyright (C) 2014  Julio Biason
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""The main page."""

import logging

from flask import Blueprint
from flask import render_template
from flask import current_app

from pony.orm import count
from pony.orm import select

from tagallery.database import Image

log = logging.getLogger('tragallery.index')

index = Blueprint('index',
                  __name__)


@index.route('/', defaults={'page': 1})
@index.route('/<int:page>')
def all_images(page):
    return render_template('index.html',
                           total_images=_image_count(),
                           thumbnail_size=current_app.config['THUMBNAIL_SIZE'])


def _image_count():
    """Return the number of images, either from the db or in the app
    "cache"."""
    total_images = current_app.config['_IMAGES']
    if not total_images:
        total = list(select(count(record) for record in Image))
        log.debug(total)
        total_images = total[0]
        current_app.config['_IMAGES'] = total_images

    log.debug('{0} images in the database'.format(total_images))
    return total_images

tagallery/blueprints/upload.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

#   Tagallery, a tag based web gallery
#   Copyright (C) 2014  Julio Biason
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Image upload module."""

import os
import os.path
import datetime
import logging

from werkzeug import secure_filename

from flask import Blueprint
from flask import render_template
# from flask import redirect
from flask import url_for
from flask import current_app
from flask import request
from flask import jsonify
from flask import flash
from flask import abort
from flask import send_from_directory

from flask.ext.login import login_required

from PIL import Image as ImageFile

from tagallery.database import Image
from tagallery.database import Tag

from tagallery.storage import partition
from tagallery.storage import thumbname

upload = Blueprint('upload', __name__)

LOG = logging.getLogger('tagallery.blueprints.upload')


@upload.route('/', methods=['GET'])
@login_required
def dashboard():
    return render_template('upload/upload.html')
    # return redirect(url_for("upload.from_browser"))
    # return render_template('upload/dashboard.html')


@upload.route('/browser/upload/', methods=['POST'])
@login_required
def upload_file():
    fileobj = request.files['file']
    response = {'status': 'UNKNOWN', 'filename': None}
    if fileobj:
        filename = secure_filename(fileobj.filename)
        path = os.path.join(current_app.config['IMAGE_PATH'],
                            partition(filename))
        try:
            os.makedirs(path)
        except os.error:
            pass    # already exists

        final_filename = os.path.join(path, filename)
        fileobj.save(final_filename)
        response['status'] = 'OK'
        response['filename'] = final_filename

        LOG.debug('File {file} saved on disk'.format(file=final_filename))

    return jsonify(response)


@upload.route('/save/', methods=['POST'])
@login_required
def save():
    filename = request.values.get('filename')
    title = request.values.get('title')
    form_tags = request.values.get('tags', '').split(',')

    if len(form_tags) == 0:
        flash('Must have at least one tag', 'alert')

    tags = []
    for single_tag in form_tags:
        if not single_tag:
            continue

        LOG.debug('Searching for tag {0}'.format(single_tag))
        tag = Tag.get(tag=single_tag)
        if not tag:
            LOG.debug('Tag {0} not found, creating new'.format(single_tag))
            tag = Tag(tag=single_tag)
        tags.append(tag)

    Image(title=title,
          tags=tags,
          created_at=datetime.datetime.utcnow(),
          filename=filename)

    LOG.debug('Image saved')

    thumb = ImageFile.open(filename)
    size = current_app.config['THUMBNAIL_SIZE']
    thumb.thumbnail((size, size),
                    ImageFile.ANTIALIAS)
    thumb.save(thumbname(filename))

    LOG.debug('Thumbnail {0} created'.format(thumbname(filename)))

    flash('Upload completed with success')

    return render_template('upload/from_browser.html', source='browser')


@upload.route('/queue/', methods=['GET'])
@login_required
def queue():
    """Return a list of files waiting in the incoming directory."""
    root = os.path.expanduser(current_app.config['IMAGE_QUEUE'])
    LOG.debug('Queue dir: {0}'.format(root))
    result = {'status': 'OK', 'files': []}

    try:
        for filename in os.listdir(root):
            LOG.debug('Found file: {0}'.format(filename))

            # pruning unwanted files
            if not filename.lower().endswith('.png') and \
                    not filename.lower().endswith('.jpg') and \
                    not filename.lower().endswith('.gif'):
                continue

            result['files'].append({
                'url': url_for('upload.serve_queue', filename=filename),
                'title': filename
            })
    except OSError:
        # the queue directory does not exist
        pass

    return jsonify(result)


@upload.route('/queue/image/', methods=['GET'])
@login_required
def serve_queue():
    """Serve an image directly from the queue."""
    filename = request.values.get('filename')
    if not filename:
        abort(400)

    queue_dir = os.path.expanduser(current_app.config['IMAGE_QUEUE'])

    return send_from_directory(queue_dir, filename)

tagallery/blueprints/users.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-

#   Tagallery, a tag based web gallery
#   Copyright (C) 2014  Julio Biason
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""User management."""

from flask import Blueprint
from flask import render_template
from flask import request
from flask import flash
from flask import redirect
from flask import url_for

from flask.ext.login import login_user
from flask.ext.login import logout_user

from tagallery.database import User

# from pony.orm import db_session
from pony.orm import ObjectNotFound

import logging
import crypt

users = Blueprint('users', __name__)

log = logging.getLogger('tagallery.users')


@users.route('/login/', methods=['GET'])
def show_login():
    return render_template('users/login.html')


@users.route('/login/', methods=['POST'])
def make_login():
    username = request.values.get('username')
    password = request.values.get('password')

    if not username:
        log.debug('Missing username')
        flash('Username is required', 'alert')
        return render_template('users/login.html', username=username)

    if not password:
        log.debug('Missing password')
        flash('Password is required', 'alert')
        return render_template('users/login.html', username=username)

    salt = username[0] + username[-1]

    crypted = crypt.crypt(password, salt)
    user = None
    try:
        user = User.get(login=username, password=crypted)
    except ObjectNotFound:
        user = None

    log.debug('User = {0}'.format(user))
    if not user:
        flash('Invalid username/password', 'alert')
        return render_template('users/login.html', username=username)

    login_user(user, remember=True)
    return redirect(request.args.get('next') or url_for('index.all_images'))


@users.route('/logout/', methods=['GET'])
def logout():
    logout_user()
    return redirect(url_for('index.all_images'))

tagallery/templates/base.html
<!DOCTYPE html>

<!--[if IE 8]>         <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->
	<head>
		<meta chatset='utf-8'>
		<meta name='viewport' content='width=device-width'>

		<title>Tagallery</title>

		<link rel='stylesheet' href='{{ url_for("static", filename="css/normalize.css") }}'>
		<link rel='stylesheet' href='{{ url_for("static", filename="css/foundation.min.css") }}'>
		<link rel='stylesheet' href='{{ url_for("static", filename="css/tagallery.css") }}'>
		<link rel='stylesheet' href='{{ url_for("static", filename="css/select2.css") }}'>

		<script src='{{ url_for("static", filename="js/vendor/custom.modernizr.js") }}'></script>
	</head>

	<body>
		<nav class='top-bar' data-topbar>
			<ul class='title-area'>
				<li class='name'>
					<h1><a href='/'>Tagallery</a></h1>
				</li>
			</ul>

			<section class='top-bar-section'>
				<ul class='left'>
					<li><a href='#'>All tags</a></li>
				</ul>

				<ul class='right'>
					{% if current_user.is_authenticated() %}
						<li class='has-dropdown'>
							<a href='#'>Logged as {{ current_user.login }}</a>
							<ul class='dropdown'>
								<li><a href='{{ url_for("upload.dashboard") }}'>Upload</a></li>
								<li><a href="#">Auto-tags</a></li>
								<li class='divider'></li>
								<li><a href='{{ url_for("users.logout") }}'>Logout</a></li>
							</ul>
						</li>
					{% else %}
						<li><a href='{{ url_for("users.show_login") }}'>Login</a></li>
					{% endif %}
				</ul>
			</section>
		</nav>

		{% block styles %}{% endblock styles %}

		{% with messages = get_flashed_messages(with_categories=True) %}
			{% if messages %}
				{% for category, message in messages %}
					<div class='row'>
						<div class='large-12 columns'>
							<div data-alert class='alert-box radius {{ category }}'>
								{{ message }}
							</div>
						</div>
					</div>
				{% endfor %}
			{% endif %}
		{% endwith %}

		<div class='row'>
			<div class='large-12 columns'>
				<div id='content'>
					{% block content %}
					{% endblock content %}
				</div>
			</div>
		</div>

		<script src="{{ url_for("static", filename="js/vendor/jquery.js") }}"></script>
		<script src='{{ url_for("static", filename="js/foundation.min.js") }}'></script>
		<script src='{{ url_for("static", filename="js/select2.min.js") }}'></script>
		<script>$(document).foundation();</script>

		<script src='{{ url_for("static", filename="js/tagallery.js") }}'></script>

		{% block scripts %}{% endblock %}
	</body>
</html>

{# vim:set ft=htmldjango: #}

tagallery/templates/index.html
{% extends "base.html" %}
{% block content %}
<ul id='images'>
</div>
{% endblock %}

{% block scripts %}
<script>
	var images = {{ total_images }};
	var size = {{ thumbnail_size }};

	$(function() {
		$(window).on('resize', function () {
			recalc(images, size);
		});
		recalc(images, size);
	});
</script>
{% endblock scripts %}

tagallery/templates/layout.html
<!doctype html>
<html>
	<head>
		<title>Tagallery</title>

		<script type='text/javascript' src='https://ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js'></script>

		<link rel='stylesheet' type='text/css' href='{{ url_for("static", filename="style.css") }}'>
	</head>

	<body>
		<div id='header'>
			Tagallery
		</div>

		<div id='body'>
			{% block body %}{% endblock %}
		</div>
	</body>
</html>